name: firebase_login_signup
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  get_cli: any
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.5.1
  firebase_storage: ^11.1.0



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets :
    - assets/


